---
- hosts: core

  vars_prompt: 
    - name: "JavaKeyStorePassword" 
      prompt: "Enter password for Cobalt Strike Java Keystore password" 
      private: yes 

  vars:
    allowedIPs:
      - <IP1>
      - <IP2>
      - <IP3>

    #If your Client is running on Windows/Mac, download Windows/Mac and Linux installation
    cobaltstrikeInstallation: <cobaltstrike-trial.tgz>

    #Flat text file with key
    cobaltstrikeLicense: <cobalt_license.txt>

    #don't forget trailing slash!!
    userHomePath: </home/username/>
    #userHomePath: </root/>

    domain: <domain>

    fullchainPath: "<path on Ansible Server>/<fullchain.pem>"
    privkeyPath: "<path on Ansible Server>/<privkey.pem>"

    required_packages:
      - libssl-dev
      - libffi-dev
      - python-dev
      - build-essential
      - python-pip
      - ufw
      - openjdk-11-jdk

  tasks:
    - name: Update APT package cache
      become: true
      apt: 
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade APT to the latest packages
      become: true
      apt: 
        upgrade: safe

    - name: Install required packages
      become: true
      apt: 
        state: present
        pkg: "{{ required_packages}}"

    #Install Cobalt Strike
    - name: CobaltStrike - Upload Cobalt Strike installation package from ansible host
      copy:
        src: "{{ cobaltstrikeInstallation }}"
        dest: "{{ userHomePath }}cobaltstrike-trial.tgz"

    - name: CobaltStrike - Unzip Cobalt Strike installation package to /opt
      unarchive:
        src: "{{ userHomePath }}cobaltstrike-trial.tgz"
        dest: "{{ userHomePath }}"
        remote_src: yes
      become: yes

    - name: CobaltStrike - Upload Cobalt Strike license key to ~/root
      copy:
        src: "{{ cobaltstrikeLicense }}"
        dest: /root/.cobaltstrike.license
      become: true

    - name: CobaltStrike - Update Cobalt Strike
      become: true
      shell: "{{ userHomePath }}cobaltstrike/update"
      args:
        chdir: "{{ userHomePath }}cobaltstrike"

    - name: CobaltStrike - Change CobaltStrike management port from default
      become: true
      replace:
        dest: "{{ userHomePath }}cobaltstrike/teamserver"
        regexp: 50050
        replace: 42424

    - name: CobaltStrike - Firewall rule to restrict access to CobaltStrike management port on 42424
      become: true
      ufw: 
        rule: allow
        port: 42424
        proto: tcp
        src: "{{ item }}"
      with_items:
        - "{{ allowedIPs }}"

    - name: Upload SSL fullchain certificate file from Ansible Server
      copy:
        src: "{{ fullchainPath }}"
        dest: "{{ domain }}_fullchain.pem"
        
    - name: Upload SSL privkey PEM file from Ansible Server
      copy:
        src: "{{ privkeyPath }}"
        dest: "{{ domain }}_privkey.pem"
        
    - name: Build PKCS12 .p12 cert
      become: true
      shell: "openssl pkcs12 -export -in {{ domain }}_fullchain.pem -inkey {{ domain }}_privkey.pem -out {{ domain }}.p12 -name {{ domain }} -passout pass:{{ JavaKeyStorePassword }}"

    - name: CobaltStrike - Build Java keystore via keytool to enable SSL comms
      become: true
      shell: "keytool -importkeystore -deststorepass {{ JavaKeyStorePassword }} -destkeypass {{ JavaKeyStorePassword }} -destkeystore {{ domain }}.store -srckeystore {{ domain }}.p12 -srcstoretype PKCS12 -srcstorepass {{ JavaKeyStorePassword }} -alias {{ domain }}"      

    - name: Download Cobalt Srike Jar File to ansible host
      fetch:
        src: "{{ userHomePath }}cobaltstrike/cobaltstrike.jar"
        dest: cobaltstrike.jar
        flat: yes
  
    - name: Download Cobalt Srike Java client to ansible host
      fetch:
        src: "{{ userHomePath }}cobaltstrike/cobaltstrike"
        dest: cobaltstrike
        flat: yes

    - name: Download Cobalt Srike auth file to ansible host
      fetch:
        src: "{{ userHomePath }}cobaltstrike/cobaltstrike.auth"
        dest: cobaltstrike.auth
        flat: yes
